name: Execute load test from a file name

on:
  workflow_call:
    inputs:
      script-file:
        required: true
        type: string

jobs:
  load-test:
    name: Run LOAD TEST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup test-script.yml
        working-directory: ./load-test
        run: |
          rm -f test-script.yml
          mv ${{ inputs.script-file }} test-script.yml

      - name: Build and Up Worker and Scheduler Services
        working-directory: ./load-test
        run: |
          docker compose up -d scheduler worker

      - name: Execute Load-test
        working-directory: ./load-test
        run: |
          docker compose up artillery
      
      - name: 🎬 📈 Track Load-test Result ✅
        working-directory: ./load-test
        run: |
          docker compose logs --tail=150 artillery

      - name: Shutdown all services
        working-directory: ./load-test
        run: |
          docker compose down
      